// sharedState.js
import { reactive } from "vue";

export const state = reactive({
  musicSheets: [
    {
      id: 1,
      title: "Song 1",
      composer: "Composer A",
      genres: ["Rock"],
      year: 2000,
      instruments: ["Guitar"],
      key: "C",
      filetype: "PDF",
      link: "/sheets/song1.pdf",
    },
    {
      id: 2,
      title: "Song 2",
      composer: "Composer B",
      genres: ["Pop"],
      year: 2005,
      instruments: ["Piano"],
      key: "D",
      filetype: "PDF",
      link: "/sheets/song2.pdf",
    },
    {
      id: 3,
      title: "Song 3",
      composer: "Composer C",
      genres: ["Classical"],
      year: 1970,
      instruments: ["Drums"],
      key: "F",
      filetype: "PDF",
      link: "/sheets/song3.pdf",
    },
    {
      id: 4,
      title: "Song 4",
      composer: "Composer D",
      genres: ["Rock", "Pop"],
      year: 2015,
      instruments: ["Guitar", "Piano"],
      key: "G",
      filetype: "PDF",
      link: "/sheets/song4.pdf",
    },
    {
      id: 5,
      title: "Song 5",
      composer: "Composer E",
      genres: ["Rock", "Classical"],
      year: 1960,
      instruments: ["Guitar", "Drums"],
      key: "A",
      filetype: "PDF",
      link: "/sheets/song5.pdf",
    },
    {
      id: 6,
      title: "Song 6",
      composer: "Composer F",
      genres: ["Pop", "Classical"],
      year: 2021,
      instruments: ["Piano", "Drums"],
      key: "B",
      filetype: "PDF",
      link: "/sheets/song6.pdf",
    },
    {
      id: 7,
      title: "Song 7",
      composer: "Composer G",
      genres: ["Rock", "Pop", "Classical"],
      year: 1857,
      instruments: ["Guitar", "Piano", "Drums"],
      key: "C",
      filetype: "PDF",
      link: "/sheets/song7.pdf",
    },
    {
      id: 8,
      title: "Song 8",
      composer: "Composer H",
      genres: ["Rock", "Pop", "Classical"],
      year: 2023,
      instruments: ["Guitar", "Piano", "Drums"],
      key: "D",
      filetype: "PDF",
      link: "/sheets/song8.pdf",
    },
    // Add 15-20 more items here
    // Add more music sheets here
  ],
  selectedMusicSheet: null, // Store the currently selected music sheet
});
